const fs = require('fs');
const path = 'public/module/admin/exam_question_generation.html';
let content = fs.readFileSync(path, 'utf8');

// Find: "generatedItems = [];" that is followed by setGenerating
// This is the start of the manual mode processing block
const startMarker = '          generatedItems = [];\n\n          setGenerating(loading, true, loadingText';
const startIdx = content.indexOf(startMarker);
if (startIdx === -1) {
  console.log('ERROR: Could not find start marker');
  process.exit(1);
}

// Find: "return;\n        }\n\n        // -- AUTO mode"
// This is the end of the manual mode block
const endMarker = '          return;\n        }\n\n        // -- AUTO mode';
const endIdx = content.indexOf(endMarker);
if (endIdx === -1) {
  // Try with \r\n
  const endMarker2 = '          return;\r\n        }\r\n\r\n        // -- AUTO mode';
  const endIdx2 = content.indexOf(endMarker2);
  if (endIdx2 === -1) {
    console.log('ERROR: Could not find end marker');
    // Debug
    const autoIdx = content.indexOf('// -- AUTO mode');
    if (autoIdx !== -1) {
      console.log('Found AUTO mode at char ' + autoIdx);
      console.log('Context: ' + JSON.stringify(content.slice(autoIdx - 100, autoIdx + 50)));
    }
    process.exit(1);
  }
}

const actualEndIdx = content.indexOf(endMarker) !== -1 ? content.indexOf(endMarker) : content.indexOf('          return;\r\n        }\r\n\r\n        // -- AUTO mode');
// We want to keep "return;\n        }\n\n        // -- AUTO mode" and only replace up to and including "return;"
// Actually we want to replace from startIdx to just after "return;" (not including the "}")
const returnEndIdx = actualEndIdx + '          return;'.length;

console.log('Replacing from char ' + startIdx + ' to ' + returnEndIdx);

// Build replacement - using string concatenation to avoid template literal escape issues
var NL = '\n';
var BSN = String.fromCharCode(92) + 'n'; // literal \n for the output file
var BT = String.fromCharCode(96); // backtick

var r = '';
r += '          generatedItems = [];' + NL;
r += '' + NL;
r += '          setGenerating(loading, true, loadingText,' + NL;
r += "            'Sending to <strong>Mistral AI</strong> for arrangement...');" + NL;
r += '' + NL;
r += '          try {' + NL;
r += '            const BATCH_SIZE = 5;' + NL;
r += '            const keys = await loadMistralApiKeys();' + NL;
r += '' + NL;
r += '            const totalBatches = Math.ceil(blocks.length / BATCH_SIZE);' + NL;
r += '            const batches = [];' + NL;
r += '            for (let i = 0; i < blocks.length; i += BATCH_SIZE) {' + NL;
r += '               batches.push({' + NL;
r += '                  index: batches.length,' + NL;
r += '                  blocks: blocks.slice(i, i + BATCH_SIZE),' + NL;
r += '                  startIndex: i' + NL;
r += '               });' + NL;
r += '            }' + NL;
r += '' + NL;
r += '            let batchGroupIndex = 0;' + NL;
r += '            const batchResults = new Array(totalBatches).fill(null);' + NL;
r += '' + NL;
r += '            // -- SMART RESUME: skip already-completed batches --' + NL;
r += "            const savedPartial = localStorage.getItem('elite_exam_partial_gen');" + NL;
r += '            if (savedPartial) {' + NL;
r += '               try {' + NL;
r += '                  const partial = JSON.parse(savedPartial);' + NL;
r += '                  if (partial.length > 0 && partial.length < blocks.length) {' + NL;
r += '                     generatedItems = partial;' + NL;
r += '                     for (let i = 0; i < partial.length; i += BATCH_SIZE) {' + NL;
r += '                        const bIdx = Math.floor(i / BATCH_SIZE);' + NL;
r += '                        batchResults[bIdx] = partial.slice(i, i + BATCH_SIZE);' + NL;
r += '                     }' + NL;
r += '                     batchGroupIndex = Math.floor(partial.length / BATCH_SIZE);' + NL;
r += "                     showToast('Resuming from question ' + (partial.length + 1) + '...', 'info');" + NL;
r += '                     // Show already-loaded preview immediately' + NL;
r += '                     renderExamPreview(previewList, generatedItems);' + NL;
r += '                  } else if (partial.length >= blocks.length) {' + NL;
r += '                     generatedItems = partial;' + NL;
r += '                     batchGroupIndex = totalBatches;' + NL;
r += '                  }' + NL;
r += '               } catch (e) {' + NL;
r += '                  generatedItems = [];' + NL;
r += '               }' + NL;
r += '            }' + NL;
r += '' + NL;
r += '            // -- WORKER POOL WITH FAILOVER + ETA --' + NL;
r += '            const batchQueue = [];' + NL;
r += '            for (let i = batchGroupIndex; i < batches.length; i++) {' + NL;
r += '               batchQueue.push(batches[i]);' + NL;
r += '            }' + NL;
r += '            let queuePointer = 0;' + NL;
r += '            let hasFatalError = false;' + NL;
r += '            let fatalErrorMessage = ' + "'';" + NL;
r += '            const startTime = Date.now();' + NL;
r += '            let lastRenderedCount = generatedItems.length;' + NL;
r += '' + NL;
r += '            // Append-only UI update (no flashing)' + NL;
r += '            const updateUI = () => {' + NL;
r += '                let currentFlatted = [];' + NL;
r += '                for (let i = 0; i < batchResults.length; i++) {' + NL;
r += '                    if (batchResults[i]) {' + NL;
r += '                        currentFlatted = currentFlatted.concat(batchResults[i]);' + NL;
r += '                    } else {' + NL;
r += '                        break;' + NL;
r += '                    }' + NL;
r += '                }' + NL;
r += '' + NL;
r += '                generatedItems = currentFlatted.map((item, idx) => ({' + NL;
r += '                    num: idx + 1,' + NL;
r += "                    question: item.question || ('Question ' + (idx + 1))," + NL;
r += '                    options: (item.options || []).map(o => ({ letter: o.letter, text: o.text, correct: !!o.correct })),' + NL;
r += '                    difficulty: item.difficulty || diff,' + NL;
r += "                    explanation: item.explanation || 'No explanation provided.'," + NL;
r += '                }));' + NL;
r += '' + NL;
r += "                localStorage.setItem('elite_exam_partial_gen', JSON.stringify(generatedItems));" + NL;
r += '' + NL;
r += '                // Only append NEW cards (prevents preview from flashing)' + NL;
r += '                const newItems = generatedItems.slice(lastRenderedCount);' + NL;
r += '                if (newItems.length > 0) {' + NL;
r += '                  const fragment = document.createDocumentFragment();' + NL;
r += '                  newItems.forEach(item => {' + NL;
r += "                    const card = document.createElement('div');" + NL;
r += "                    card.className = 'preview-card';" + NL;
r += "                    card.style.animationDelay = (item.num * 0.02) + 's';" + NL;
r += "                    card.innerHTML = '<div class=\"preview-card-header\">'" + NL;
r += "                      + '<span class=\"preview-card-num\">Q' + item.num + '</span>'" + NL;
r += "                      + '<span class=\"preview-card-diff diff-' + item.difficulty + '\">' + item.difficulty + '</span>'" + NL;
r += "                      + '</div>'" + NL;
r += "                      + '<p class=\"preview-card-q\">' + item.question + '</p>'" + NL;
r += "                      + '<div class=\"preview-options\">'" + NL;
r += "                      + item.options.map(o => '<div class=\"preview-opt ' + (o.correct ? 'correct' : '') + '\">' + o.letter + '. ' + o.text + '</div>').join('')" + NL;
r += "                      + '</div>';" + NL;
r += '                    fragment.appendChild(card);' + NL;
r += '                  });' + NL;
r += '                  previewList.appendChild(fragment);' + NL;
r += '                  lastRenderedCount = generatedItems.length;' + NL;
r += '                }' + NL;
r += '' + NL;
r += '                // Calculate ETA' + NL;
r += '                const done = generatedItems.length;' + NL;
r += '                const remaining = blocks.length - done;' + NL;
r += '                const elapsed = (Date.now() - startTime) / 1000;' + NL;
r += '                const doneThisSession = done - (batchGroupIndex * BATCH_SIZE);' + NL;
r += "                let etaText = '';" + NL;
r += '                if (doneThisSession > 0) {' + NL;
r += '                  const secsPerQ = elapsed / doneThisSession;' + NL;
r += '                  const etaSecs = Math.round(secsPerQ * remaining);' + NL;
r += '                  if (etaSecs >= 60) {' + NL;
r += "                    etaText = ' | ~' + Math.floor(etaSecs / 60) + 'm ' + (etaSecs % 60) + 's left';" + NL;
r += '                  } else {' + NL;
r += "                    etaText = ' | ~' + etaSecs + 's left';" + NL;
r += '                  }' + NL;
r += '                }' + NL;
r += '' + NL;
r += '                updatePreviewStats(previewStats, done, subject, modelId);' + NL;
r += "                previewStatus.textContent = done + ' / ' + blocks.length + ' done | ' + remaining + ' remaining' + etaText;" + NL;
r += '                previewList.scrollTop = previewList.scrollHeight;' + NL;
r += '            };' + NL;
r += '' + NL;
r += '            // Each worker pulls from the shared queue' + NL;
r += '            const worker = async (keyToUse, keyIndex) => {' + NL;
r += '                while (!hasFatalError) {' + NL;
r += '                    if (queuePointer >= batchQueue.length) break;' + NL;
r += '                    const batch = batchQueue[queuePointer++];' + NL;
r += '' + NL;
r += '                    // Skip if already completed' + NL;
r += '                    if (batchResults[batch.index]) continue;' + NL;
r += '' + NL;
r += "                    const chunkText = batch.blocks.join('" + BSN + BSN + "');" + NL;
r += '' + NL;
r += '                    const promptLines = [' + NL;
r += "                      'You are a formatting assistant. The admin has pasted exam questions below.'," + NL;
r += "                      ''," + NL;
r += "                      'CRITICAL RULES:'," + NL;
r += "                      '- Do NOT change, rephrase, or alter any question text, option text, answer, or explanation.'," + NL;
r += "                      '- Do NOT add, remove, or reorder questions.'," + NL;
r += "                      '- Your ONLY job is to read each question block and output it as valid JSON.'," + NL;
r += "                      '- Return a JSON array with NO markdown, NO code fences -- pure JSON only.'," + NL;
r += "                      '- Each object must have exactly these keys:'," + NL;
r += '                      \'    "question"     -- the question text exactly as written (strip leading numbers like "1.","1)")\'' + ',' + NL;
r += '                      \'    "options"      -- array of {letter, text, correct:bool}\'' + ',' + NL;
r += "                      '    \"difficulty\"   -- use \"' + (diff === 'mixed' ? 'medium' : diff) + '\"'," + NL;
r += "                      '    \"explanation\"  -- explanation text if present, else \"No explanation provided.\"'," + NL;
r += "                      '- Mark correct:true on the option whose letter matches the Answer line.'," + NL;
r += "                      ''," + NL;
r += "                      'PASTED QUESTIONS:'," + NL;
r += '                      chunkText' + NL;
r += '                    ];' + NL;
r += "                    const manualPrompt = promptLines.join('" + BSN + "');" + NL;
r += '' + NL;
r += '                    let retries = 3;' + NL;
r += '                    let delay = 1500;' + NL;
r += '                    let success = false;' + NL;
r += '' + NL;
r += '                    while (!success && !hasFatalError) {' + NL;
r += '                        try {' + NL;
r += '                           const rawText = await callMistralApiWithKey(keyToUse, modelId, manualPrompt);' + NL;
r += '                           let clean = rawText.trim();' + NL;
r += '' + NL;
r += '                           // Strip markdown fences' + NL;
r += "                           if (clean.startsWith('```')) {" + NL;
r += "                             const nl = clean.indexOf('" + BSN + "');" + NL;
r += '                             clean = nl !== -1 ? clean.slice(nl + 1) : clean;' + NL;
r += '                           }' + NL;
r += "                           if (clean.endsWith('```')) {" + NL;
r += "                             const nl = clean.lastIndexOf('" + BSN + "');" + NL;
r += '                             clean = nl !== -1 ? clean.slice(0, nl) : clean;' + NL;
r += '                           }' + NL;
r += '' + NL;
r += '                           // Fix smart/curly quotes from AI output' + NL;
r += "                           clean = clean.replace(/[" + '\u201C\u201D' + "]/g, '\"').replace(/[" + '\u2018\u2019' + "]/g, \"'\");" + NL;
r += '                           clean = clean.trim();' + NL;
r += '' + NL;
r += '                           let parsed = null;' + NL;
r += '                           try {' + NL;
r += '                             parsed = JSON.parse(clean);' + NL;
r += '                           } catch (e) {' + NL;
r += "                             const arrStart = clean.indexOf('[');" + NL;
r += "                             const arrEnd = clean.lastIndexOf(']');" + NL;
r += "                             if (arrStart === -1 || arrEnd === -1) throw new Error('AI returned invalid JSON.');" + NL;
r += '                             parsed = JSON.parse(clean.slice(arrStart, arrEnd + 1));' + NL;
r += '                           }' + NL;
r += '' + NL;
r += '                           if (!Array.isArray(parsed) || !parsed.length) {' + NL;
r += "                             throw new Error('AI returned no questions.');" + NL;
r += '                           }' + NL;
r += '' + NL;
r += '                           batchResults[batch.index] = parsed.slice(0, batch.blocks.length);' + NL;
r += '                           success = true;' + NL;
r += '                           updateUI();' + NL;
r += '' + NL;
r += '                        } catch (err) {' + NL;
r += '                           retries--;' + NL;
r += '                           if (retries <= 0) {' + NL;
r += '                               // FAILOVER: push batch back to queue for another API key' + NL;
r += "                               console.warn('Key ' + keyIndex + ' failed batch ' + batch.index + ': ' + err.message + '. Re-queuing for another key.');" + NL;
r += '                               batchQueue.push(batch);' + NL;
r += '                               break;' + NL;
r += '                           }' + NL;
r += '                           await new Promise(r => setTimeout(r, delay));' + NL;
r += '                           delay = Math.min(delay * 2, 16000);' + NL;
r += '                        }' + NL;
r += '                    }' + NL;
r += '                }' + NL;
r += '            };' + NL;
r += '' + NL;
r += '            // Launch one worker per API key' + NL;
r += '            await Promise.all(keys.map((key, idx) => worker(key, idx)));' + NL;
r += '' + NL;
r += '            // Check for incomplete batches' + NL;
r += '            const incomplete = batchResults.filter(r => r === null).length;' + NL;
r += '            if (incomplete > 0) {' + NL;
r += "                throw new Error(incomplete * BATCH_SIZE + ' questions could not be generated. Try again.');" + NL;
r += '            }' + NL;
r += '' + NL;
r += '            // Final full render' + NL;
r += '            renderExamPreview(previewList, generatedItems);' + NL;
r += '' + NL;
r += '            window._examAutoRetryCount = 0;' + NL;
r += '            setGenerating(loading, false);' + NL;
r += "            localStorage.removeItem('elite_exam_partial_gen');" + NL;
r += "            previewStatus.textContent = generatedItems.length + ' questions arranged. Done!';" + NL;
r += "            btnSend.classList.add('visible');" + NL;
r += '            showToast(' + "'Arranged ' + generatedItems.length + ' questions for \"' + title + '\"', 'success'" + ');' + NL;
r += '          } catch (err) {' + NL;
r += '            setGenerating(loading, false);' + NL;
r += '            console.error(err);' + NL;
r += '            window._examAutoRetryCount = (window._examAutoRetryCount || 0) + 1;' + NL;
r += '            if (window._examAutoRetryCount <= 5) {' + NL;
r += "               showToast('Error: ' + err.message + '. Auto-retrying (' + window._examAutoRetryCount + '/5) in 3s...', 'error');" + NL;
r += '               setTimeout(() => {' + NL;
r += "                 const btn = document.getElementById('btn-generate');" + NL;
r += '                 if (btn && !btn.disabled) btn.click();' + NL;
r += '               }, 3000);' + NL;
r += '            } else {' + NL;
r += "               showToast('Fatal Error: ' + err.message, 'error');" + NL;
r += '            }' + NL;
r += '          } finally {' + NL;
r += '            btnGenerate.disabled = false;' + NL;
r += '          }' + NL;
r += '          return;';

content = content.substring(0, startIdx) + r + content.substring(returnEndIdx);

fs.writeFileSync(path, content, 'utf8');
console.log('SUCCESS - file written');
